package fabrico.nova.optics.model.constants;

public enum UserState {

    MAIN_MENU,
    CUSTOMER_DATA_COLLECTION,
    CUSTOMER_NAME,
    CUSTOMER_NUMBER,
    LINZA_WARNING,
    LINZA_NAME,
    LINZA_CUSTOMER_NAME,
    ADMIN_MENU,
    USER_REGISTER,
    SAVE_USER_CONTACT,
    DOCTOR_SEEING,
    POST_NEWS,
    ADD_GLASSES,
    ADD_LENSES,
    CANCEL,
    CHANEL_STATE
}
